version: '3.8'

services:
    mymongodb:
        image: 'mongo'
        ports:
            - '27017:27017'
        # our mongodb depends on volume to keep the data alive.
        volumes:
            - database:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: 'bg'
            MONGO_INITDB_ROOT_PASSWORD: '123456'
    backend:
        build: ./backend
        restart: always
        ports:
            - '3333:3333'
        depends_on:
            - mymongodb
        volumes:
            - ./backend:/app
    frontend:
        build: ./frontend
        ports:
            - '3000:3000'
        volumes:
            - ./frontend/src:/app/src
        # allow interactive mode
        stdin_open: true
        tty: true
        depends_on:
            - backend
volumes:
    database:
